import type { RunResult } from './game/game.js';

const STORAGE_KEY = 'pocket-hell:scores:v2';
const PLAYER_KEY = 'pocket-hell:player:v2';
const CACHE_KEY = 'pocket-hell:community:v2';
const REPOSITORY = 'davidUSboy/pocket-hell';
const MAX_LOCAL_ENTRIES = 20;
const CACHE_LIFETIME = 5 * 60 * 1000;
const SCORE_PREFIX = '[POCKET HELL SCORE]';
const SCORE_MARKER = '<!-- POCKET_HELL_SCORE_V2 -->';

export interface ScoreEntry {
  id: string;
  player: string;
  score: number;
  time: number;
  kills: number;
  health: number;
  ammo: number;
  createdAt: string;
  source: 'local' | 'github';
  url?: string;
  githubUser?: string;
}

interface GitHubIssue {
  id: number;
  title: string;
  body: string | null;
  html_url: string;
  created_at: string;
  pull_request?: unknown;
  user: { login: string } | null;
}

interface CommunityCache {
  savedAt: number;
  entries: ScoreEntry[];
}

export class LeaderboardService {
  private localEntries = this.readLocalEntries();
  private communityEntries = this.readCommunityCache();

  getPlayerName(): string {
    try {
      return this.sanitizeName(localStorage.getItem(PLAYER_KEY) ?? 'PLAYER 1');
    } catch {
      return 'PLAYER 1';
    }
  }

  setPlayerName(value: string): string {
    const name = this.sanitizeName(value);
    try {
      localStorage.setItem(PLAYER_KEY, name);
    } catch {
      // Storage can be unavailable in private or embedded browsers.
    }
    return name;
  }

  getLocalEntries(): ScoreEntry[] {
    return [...this.localEntries];
  }

  getCommunityEntries(): ScoreEntry[] {
    return [...this.communityEntries];
  }

  getBestLocal(): ScoreEntry | null {
    return this.localEntries[0] ?? null;
  }

  recordWin(result: RunResult, playerName: string): ScoreEntry {
    const entry: ScoreEntry = {
      id: result.runId,
      player: this.sanitizeName(playerName),
      score: result.score,
      time: result.timeSeconds,
      kills: result.kills,
      health: result.health,
      ammo: result.ammo,
      createdAt: new Date().toISOString(),
      source: 'local',
    };

    this.localEntries = [entry, ...this.localEntries.filter((item) => item.id !== entry.id)]
      .sort(this.compareEntries)
      .slice(0, MAX_LOCAL_ENTRIES);
    this.persistLocalEntries();
    return entry;
  }

  async fetchCommunity(force = false): Promise<ScoreEntry[]> {
    if (!force && this.communityEntries.length > 0) {
      return this.getCommunityEntries();
    }

    const endpoint = `https://api.github.com/repos/${REPOSITORY}/issues?state=all&per_page=100&sort=created&direction=desc`;
    const response = await fetch(endpoint, {
      headers: {
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
      },
    });

    if (!response.ok) {
      throw new Error(`GitHub API ${response.status}`);
    }

    const issues = (await response.json()) as GitHubIssue[];
    this.communityEntries = issues
      .filter((issue) => !issue.pull_request)
      .map((issue) => this.parseIssue(issue))
      .filter((entry): entry is ScoreEntry => entry !== null)
      .sort(this.compareEntries)
      .slice(0, 25);
    this.persistCommunityCache();
    return this.getCommunityEntries();
  }

  createSubmissionUrl(entry: ScoreEntry, playerName: string): string {
    const player = this.sanitizeName(playerName);
    const title = `${SCORE_PREFIX} ${player} — ${entry.score}`;
    const body = [
      SCORE_MARKER,
      '',
      '## Pocket Hell community score',
      '',
      `- **Player:** ${player}`,
      `- **Score:** ${entry.score}`,
      `- **Time:** ${entry.time.toFixed(1)}`,
      `- **Kills:** ${entry.kills}`,
      `- **Health:** ${entry.health}`,
      `- **Ammo:** ${entry.ammo}`,
      `- **Run ID:** \`${entry.id}\``,
      '- **Build:** 2.0.0',
      '',
      '> Generated by the live Pocket Hell build. Community scores use an honor system.',
    ].join('\n');

    return `https://github.com/${REPOSITORY}/issues/new?${new URLSearchParams({ title, body, labels: 'leaderboard' }).toString()}`;
  }

  private parseIssue(issue: GitHubIssue): ScoreEntry | null {
    if (!issue.title.startsWith(SCORE_PREFIX) || !issue.body?.includes(SCORE_MARKER)) {
      return null;
    }

    const readText = (label: string): string | null => {
      const escapedLabel = label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const inlineMatch = issue.body?.match(
        new RegExp(`\\*\\*${escapedLabel}:\\*\\*\\s*(.+)$`, 'im'),
      );
      const formMatch = issue.body?.match(
        new RegExp(`^###\\s+${escapedLabel}\\s*$\\n+([^\\n]+)`, 'im'),
      );
      const value = inlineMatch?.[1] ?? formMatch?.[1];
      return value?.replace(/`/g, '').trim() ?? null;
    };
    const readNumber = (label: string): number | null => {
      const value = Number(readText(label));
      return Number.isFinite(value) ? value : null;
    };

    const player = readText('Player');
    const score = readNumber('Score');
    const time = readNumber('Time');
    const kills = readNumber('Kills');
    const health = readNumber('Health');
    const ammo = readNumber('Ammo');

    if (!player || score === null || time === null || kills === null || health === null || ammo === null) {
      return null;
    }
    if (score < 0 || score > 999999 || time < 0 || time > 86400 || kills < 0 || kills > 99) {
      return null;
    }

    return {
      id: `github-${issue.id}`,
      player: this.sanitizeName(player),
      score: Math.round(score),
      time,
      kills: Math.round(kills),
      health: Math.round(health),
      ammo: Math.round(ammo),
      createdAt: issue.created_at,
      source: 'github',
      url: issue.html_url,
      githubUser: issue.user?.login,
    };
  }

  private sanitizeName(value: string): string {
    const name = value
      .normalize('NFKC')
      .toUpperCase()
      .replace(/[^A-Z0-9 _-]/g, '')
      .replace(/\s+/g, ' ')
      .trim()
      .slice(0, 16);
    return name || 'PLAYER 1';
  }

  private readonly compareEntries = (left: ScoreEntry, right: ScoreEntry): number =>
    right.score - left.score || left.time - right.time || left.createdAt.localeCompare(right.createdAt);

  private readLocalEntries(): ScoreEntry[] {
    try {
      const parsed = JSON.parse(localStorage.getItem(STORAGE_KEY) ?? '[]') as unknown;
      if (!Array.isArray(parsed)) return [];
      return parsed
        .filter((entry): entry is ScoreEntry => this.isEntry(entry))
        .map((entry) => ({ ...entry, source: 'local' as const }))
        .sort(this.compareEntries)
        .slice(0, MAX_LOCAL_ENTRIES);
    } catch {
      return [];
    }
  }

  private persistLocalEntries(): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.localEntries));
    } catch {
      // The game still works when storage is blocked.
    }
  }

  private readCommunityCache(): ScoreEntry[] {
    try {
      const cache = JSON.parse(sessionStorage.getItem(CACHE_KEY) ?? 'null') as CommunityCache | null;
      if (!cache || Date.now() - cache.savedAt > CACHE_LIFETIME || !Array.isArray(cache.entries)) return [];
      return cache.entries.filter((entry): entry is ScoreEntry => this.isEntry(entry));
    } catch {
      return [];
    }
  }

  private persistCommunityCache(): void {
    try {
      const cache: CommunityCache = { savedAt: Date.now(), entries: this.communityEntries };
      sessionStorage.setItem(CACHE_KEY, JSON.stringify(cache));
    } catch {
      // Cache is optional.
    }
  }

  private isEntry(value: unknown): value is ScoreEntry {
    if (!value || typeof value !== 'object') return false;
    const entry = value as Partial<ScoreEntry>;
    return (
      typeof entry.id === 'string' &&
      typeof entry.player === 'string' &&
      typeof entry.score === 'number' &&
      typeof entry.time === 'number' &&
      typeof entry.kills === 'number' &&
      typeof entry.health === 'number' &&
      typeof entry.ammo === 'number' &&
      typeof entry.createdAt === 'string'
    );
  }
}
